'''title'''
__title__ = 'DoubleDiamondSlots'
'''description'''
__description__ = 'A simple slot machine in Python'
'''url'''
__url__ = 'https://github.com/philipfromga/DoubleDiamond'
'''version'''
__version__ = '0.1'
'''author'''
__author__ = 'Philip Rodgers'
'''email'''
__email__ = 'philipfromga@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'
'''copyright'''
__copyright__ = 'Copyright 2023-2024 Philip Rodgers'
